name: Feature request
description: Suggest new or updated features.
title: "Suggest a new feature"
labels: [enhancement]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/hirosystems/.github/issues) for duplicate or closed issues
          required: true
        - label: I understand the [code of conduct](https://github.com/hirosystems/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [contributing guidelines](https://github.com/hirosystems/.github/blob/main/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Provide detailed information for what we should add, including relevant links to prior art, screenshots, or live demos whenever possible.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation and context
      description: Tell us why this change is needed or helpful, and what problems it may help solve.
    validations:
      required: true